"""empty message

Revision ID: 3e3bcb37411c
Revises: 309c8e65d945
Create Date: 2020-11-12 14:14:57.440986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3bcb37411c'
down_revision = '309c8e65d945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activity', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='unique')
    # ### end Alembic commands ###
